# Generated by Django 5.2.1 on 2025-05-16 06:13

import db.dictionary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hanja",
            fields=[
                (
                    "letter",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        validators=[db.dictionary.models.validate_hanja_field],
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="KoreanWord",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "word",
                    models.TextField(
                        db_index=True,
                        validators=[db.dictionary.models.validate_hangeul_field],
                    ),
                ),
                (
                    "unit",
                    models.SmallIntegerField(
                        choices=[(0, "관용구"), (1, "구"), (2, "단어"), (3, "속담")],
                        db_index=True,
                    ),
                ),
                (
                    "word_type",
                    models.SmallIntegerField(
                        choices=[
                            (-1, "-"),
                            (0, "고유어"),
                            (1, "외래어"),
                            (2, "한자어"),
                            (3, "혼종어"),
                        ],
                        db_index=True,
                        default=-1,
                    ),
                ),
                (
                    "hanja",
                    models.TextField(
                        validators=[db.dictionary.models.validate_hanja_field]
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="KoreanWordCategory",
            fields=[
                (
                    "category",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="HanjaUsage",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "hanja_id",
                        "word_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hanja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="dictionary.hanja",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hanjas",
                        to="dictionary.koreanword",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="KoreanWordSense",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "pos",
                    models.SmallIntegerField(
                        choices=[
                            (-1, "품사 없음"),
                            (0, "감탄사"),
                            (1, "관형사"),
                            (2, "구"),
                            (3, "대명사"),
                            (4, "동사"),
                            (5, "명사"),
                            (6, "보조 동사"),
                            (7, "보조 형용사"),
                            (8, "부사"),
                            (9, "수사"),
                            (10, "어미"),
                            (11, "의존 명사"),
                            (12, "접사"),
                            (13, "조사"),
                            (14, "형용사"),
                        ],
                        db_index=True,
                        default=-1,
                    ),
                ),
                ("definition", models.TextField()),
                ("definition_original", models.TextField()),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="senses", to="dictionary.koreanwordcategory"
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senses",
                        to="dictionary.koreanword",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
